[versions]
agp = "9.0.0"
kotlin = "2.3.10"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.0"
espressoCore = "3.6.0"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.1.4"

reviewKtx = "2.0.2"
tedVersion = "3.4.2"

composeUi = "1.10.4" # Обновлено до 1.10.4
composeMaterial3 = "1.5.0-alpha04" # Обновил до более общей версии для Material3
adaptive = "1.1.0"
lifecycleCompose = "2.9.4" # Для lifecycle-viewmodel-compose
datastore = "1.2.0"
koin = "4.1.1"

[libraries]
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeUi" }
androidx-compose-ui-unit-android = { group = "androidx.compose.ui", name = "ui-unit-android", version.ref = "composeUi" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeUi" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeUi" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "adaptive" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleCompose" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "reviewKtx" }
tedpermission = { group = "io.github.ParkSangGwon", name = "tedpermission-coroutine", version.ref = "tedVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]
compose = ["androidx-compose-ui", "androidx-activity-compose", "androidx-compose-ui-unit-android", "androidx-compose-material3", "androidx-compose-ui-tooling-preview", "androidx-compose-ui-tooling", "androidx-compose-material3-adaptive", "androidx-lifecycle-viewmodel-compose"]