package com.krayapp.dndworkaround.theme
import androidx.compose.ui.graphics.Color

val serverLoadingContainerColor = Color(0xFF414141)
val serverLoadingContentColor = Color(0xFFC2C2C2)
val serverContentColor = Color(0xFF000000)

val primaryLight = Color(0xFF00696E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9CF0F6)
val onPrimaryContainerLight = Color(0xFF004F53)
val secondaryLight = Color(0xFF4A6364)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCE8E9)
val onSecondaryContainerLight = Color(0xFF324B4C)
val tertiaryLight = Color(0xFF4E5F7D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD6E3FF)
val onTertiaryContainerLight = Color(0xFF364764)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF4FAFA)
val onBackgroundLight = Color(0xFF161D1D)
val surfaceLight = Color(0xFFF4FAFA)
val onSurfaceLight = Color(0xFF161D1D)
val surfaceVariantLight = Color(0xFFDAE4E5)
val onSurfaceVariantLight = Color(0xFF3F4949)
val outlineLight = Color(0xFF6F7979)
val outlineVariantLight = Color(0xFFBEC8C9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3232)
val inverseOnSurfaceLight = Color(0xFFECF2F2)
val inversePrimaryLight = Color(0xFF80D4D9)
val surfaceDimLight = Color(0xFFD5DBDB)
val surfaceBrightLight = Color(0xFFF4FAFA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F5)
val surfaceContainerLight = Color(0xFFE9EFEF)
val surfaceContainerHighLight = Color(0xFFE3E9E9)
val surfaceContainerHighestLight = Color(0xFFDDE4E4)


val primaryDark = Color(0xFF80D4D9)
val onPrimaryDark = Color(0xFF003739)
val primaryContainerDark = Color(0xFF004F53)
val onPrimaryContainerDark = Color(0xFF9CF0F6)
val secondaryDark = Color(0xFFB1CCCD)
val onSecondaryDark = Color(0xFF1B3436)
val secondaryContainerDark = Color(0xFF324B4C)
val onSecondaryContainerDark = Color(0xFFCCE8E9)
val tertiaryDark = Color(0xFFB6C7E9)
val onTertiaryDark = Color(0xFF1F314C)
val tertiaryContainerDark = Color(0xFF364764)
val onTertiaryContainerDark = Color(0xFFD6E3FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E1415)
val onBackgroundDark = Color(0xFFDDE4E4)
val surfaceDark = Color(0xFF0E1415)
val onSurfaceDark = Color(0xFFDDE4E4)
val surfaceVariantDark = Color(0xFF3F4949)
val onSurfaceVariantDark = Color(0xFFBEC8C9)
val outlineDark = Color(0xFF899393)
val outlineVariantDark = Color(0xFF3F4949)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDDE4E4)
val inverseOnSurfaceDark = Color(0xFF2B3232)
val inversePrimaryDark = Color(0xFF00696E)
val surfaceDimDark = Color(0xFF0E1415)
val surfaceBrightDark = Color(0xFF343A3B)
val surfaceContainerLowestDark = Color(0xFF090F10)
val surfaceContainerLowDark = Color(0xFF161D1D)
val surfaceContainerDark = Color(0xFF1A2121)
val surfaceContainerHighDark = Color(0xFF252B2B)
val surfaceContainerHighestDark = Color(0xFF303636)






